import MaruEditCore

/// Stable command identifiers for MaruEdit's static, app-level menu
/// commands. Naming follows the `domain.action` convention from
/// ROADMAP.md ADR-006 (`file.new`, `search.find`, ...).
extension CommandID {
    static let appSettings      = CommandID("app.settings")
    static let appMacroMenu     = CommandID("app.macroMenu")
    static let macroStartRecording = CommandID("macro.startRecording")
    static let macroStopRecording = CommandID("macro.stopRecording")
    static let macroPlayRecording = CommandID("macro.playRecording")
    static let macroSaveRecording = CommandID("macro.saveRecording")
    static let appHelp          = CommandID("app.help")
    static let helpMacros       = CommandID("help.macros")
    static let helpShortcuts    = CommandID("help.shortcuts")
    static let helpCheckUpdates = CommandID("help.checkUpdates")
    static let helpSupport      = CommandID("help.support")
    static let helpConfigureExternal = CommandID("help.configureExternal")
    static let helpExternal1 = CommandID("help.external1")
    static let helpExternal2 = CommandID("help.external2")
    static let helpExternal3 = CommandID("help.external3")
    static let helpExternal4 = CommandID("help.external4")
    static let helpExternal5 = CommandID("help.external5")
    static let helpExternal6 = CommandID("help.external6")
    static let otherFileTypeProfiles = CommandID("other.fileTypeProfiles")
    static let otherKeyAssignments = CommandID("other.keyAssignments")
    static let otherCommandList = CommandID("other.commandList")
    static let otherClearFindHistory = CommandID("other.clearHistory.find")
    static let otherClearReplaceHistory = CommandID("other.clearHistory.replace")
    static let otherClearGrepHistory = CommandID("other.clearHistory.grep")
    static let otherClearClipboardHistory = CommandID("other.clearHistory.clipboard")
    static let otherClearRecentFiles = CommandID("other.clearHistory.recentFiles")
    static let otherClearRecentFolders = CommandID("other.clearHistory.recentFolders")
    static let otherClearRecentWorkspaces = CommandID("other.clearHistory.recentWorkspaces")
    static let otherClearRecentEncodings = CommandID("other.clearHistory.recentEncodings")
    static let otherClearAllHistories = CommandID("other.clearHistory.all")
    static let otherToggleFreeCursor = CommandID("other.toggleFreeCursor")
    static let otherExportSettings = CommandID("other.exportSettings")
    static let otherImportSettings = CommandID("other.importSettings")
    static let otherRestoreSettings = CommandID("other.restoreSettings")
    static let otherJapaneseUserDictionary = CommandID("other.japaneseUserDictionary")
    static let fileNew          = CommandID("file.new")
    static let fileNewFromTemplate = CommandID("file.newFromTemplate")
    static let fileOpen         = CommandID("file.open")
    static let fileOpenFolder   = CommandID("file.openFolder")
    static let fileSave         = CommandID("file.save")
    static let fileSaveAs       = CommandID("file.saveAs")
    static let fileSaveAll      = CommandID("file.saveAll")
    static let fileSaveAllModified = CommandID("file.saveAllModified")
    static let fileSaveLF       = CommandID("file.saveLF")
    static let fileSaveAndClose = CommandID("file.saveAndClose")
    static let fileSaveAllAndClose = CommandID("file.saveAllAndClose")
    static let fileDiscardAndClose = CommandID("file.discardAndClose")
    static let fileDiscardAllAndClose = CommandID("file.discardAllAndClose")
    static let fileOpenCursorTargetAssociated = CommandID("file.openCursorTargetAssociated")
    static let fileOpenCursorTargetInEditor = CommandID("file.openCursorTargetInEditor")
    static let fileCloseTab     = CommandID("file.closeTab")
    static let windowNextTab    = CommandID("window.nextTab")
    static let windowPreviousTab = CommandID("window.previousTab")
    static let windowTabList = CommandID("window.tabList")
    static let windowCloseOtherTabs = CommandID("window.closeOtherTabs")
    static let windowCloseTabsLeft = CommandID("window.closeTabsLeft")
    static let windowCloseTabsRight = CommandID("window.closeTabsRight")
    static let windowFocusEditor = CommandID("window.focusEditor")
    static let windowFocusUtilityPane = CommandID("window.focusUtilityPane")
    static let fileClearRecoveryData = CommandID("file.clearRecoveryData")
    static let filePageSetup = CommandID("file.pageSetup")
    static let filePrint = CommandID("file.print")
    static let fileReload = CommandID("file.reload")
    static let fileToggleViewMode = CommandID("file.toggleViewMode")
    static let fileProperties = CommandID("file.properties")
    static let fileAppendRead = CommandID("file.appendRead")
    static let fileAppendSave = CommandID("file.appendSave")
    static let fileRename = CommandID("file.rename")
    static let fileOpenPartial = CommandID("file.openPartial")
    static let fileOpenBinary = CommandID("file.openBinary")
    static let fileProjectHistory = CommandID("file.projectHistory")
    static let fileSaveWorkspace = CommandID("file.saveWorkspace")
    static let fileOpenWorkspace = CommandID("file.openWorkspace")
    static let fileWorkspaceHistory = CommandID("file.workspaceHistory")
    static let fileCloseAndOpen = CommandID("file.closeAndOpen")
    static let searchFind       = CommandID("search.find")
    static let searchFindNext   = CommandID("search.findNext")
    static let searchReplace    = CommandID("search.replace")
    static let searchReplaceAll = CommandID("search.replaceAll")
    static let searchFindPrevious = CommandID("search.findPrevious")
    static let searchGoToLine   = CommandID("search.goToLine")
    static let searchQuickOpen  = CommandID("search.quickOpen")
    static let searchGrep       = CommandID("search.grep")
    static let searchGrepCurrentDocument = CommandID("search.grepCurrentDocument")
    static let searchGrepOpenDocuments = CommandID("search.grepOpenDocuments")
    static let searchRefineGrepResults = CommandID("search.refineGrepResults")
    static let searchOutputGrepDocument = CommandID("search.outputGrepDocument")
    static let searchClearHistory = CommandID("search.clearHistory")
    static let searchToggleCaseSensitive = CommandID("search.toggleCaseSensitive")
    static let searchToggleWholeWord = CommandID("search.toggleWholeWord")
    static let searchToggleRegex = CommandID("search.toggleRegex")
    static let searchToggleFuzzy = CommandID("search.toggleFuzzy")
    static let searchNextEditMark = CommandID("search.nextEditMark")
    static let searchPreviousEditMark = CommandID("search.previousEditMark")
    static let searchClearEditMarks = CommandID("search.clearEditMarks")
    static let searchToggleHighlight = CommandID("search.toggleHighlight")
    static let searchSelectAllMatches = CommandID("search.selectAllMatches")
    static let searchColorAllMatches = CommandID("search.colorAllMatches")
    static let searchClearMatchColors = CommandID("search.clearMatchColors")
    static let searchListAllMatches = CommandID("search.listAllMatches")
    static let searchReturnToStart = CommandID("search.returnToStart")
    static let searchSetRange = CommandID("search.setRange")
    static let searchSelectRange = CommandID("search.selectRange")
    static let searchClearRange = CommandID("search.clearRange")
    static let viewToggleSidebar = CommandID("view.toggleSidebar")
    static let viewToggleWrap = CommandID("view.toggleWrap")
    static let viewToggleSpaces = CommandID("view.toggleSpaces")
    static let viewToggleTabs = CommandID("view.toggleTabs")
    static let viewToggleLineEndings = CommandID("view.toggleLineEndings")
    static let viewToggleFullWidthSpaces = CommandID("view.toggleFullWidthSpaces")
    static let viewTabWidth2 = CommandID("view.tabWidth2")
    static let viewTabWidth4 = CommandID("view.tabWidth4")
    static let viewTabWidth8 = CommandID("view.tabWidth8")
    static let viewShowFonts = CommandID("view.showFonts")
    static let viewCustomizeMenus = CommandID("view.customizeMenus")
    static let viewToggleRuler = CommandID("view.toggleRuler")
    static let viewRulerInterval8 = CommandID("view.rulerInterval8")
    static let viewRulerInterval10 = CommandID("view.rulerInterval10")
    static let viewToggleTabStops = CommandID("view.toggleTabStops")
    static let editAddCursorAbove = CommandID("edit.addCursorAbove")
    static let editAddCursorBelow = CommandID("edit.addCursorBelow")
    static let editSelectNextOccurrence = CommandID("edit.selectNextOccurrence")
    static let editSelectAllOccurrences = CommandID("edit.selectAllOccurrences")
    static let editUndoLastAddedCursor = CommandID("edit.undoLastAddedCursor")
    static let editBeginColumnSelection = CommandID("edit.beginColumnSelection")
    static let editSelectWord = CommandID("edit.selectWord")
    static let editSelectLine = CommandID("edit.selectLine")
    static let editSelectParagraph = CommandID("edit.selectParagraph")
    static let editCopyQuoted = CommandID("edit.copyQuoted")
    static let editPasteQuoted = CommandID("edit.pasteQuoted")
    static let editClipboardHistory = CommandID("edit.clipboardHistory")
    static let editRestoreDeletion = CommandID("edit.restoreDeletion")
    static let editCorrectCapsLock = CommandID("edit.correctCapsLock")
    static let editReconvert = CommandID("edit.reconvert")
    static let editAppendCopy = CommandID("edit.appendCopy")
    static let editAppendCut = CommandID("edit.appendCut")
    static let editDeleteToLineStart = CommandID("edit.deleteToLineStart")
    static let editDeleteToLineEnd = CommandID("edit.deleteToLineEnd")
    static let editInvertSelections = CommandID("edit.invertSelections")
    static let editReserveSelections = CommandID("edit.reserveSelections")
    static let editRestoreReservedSelections = CommandID("edit.restoreReservedSelections")
    static let editBoxPaste = CommandID("edit.boxPaste")
    static let editPastePreviousClipboard = CommandID("edit.pastePreviousClipboard")
    static let editRepeatLastOperation = CommandID("edit.repeatLastOperation")
    static let editDeleteLine = CommandID("edit.deleteLine")
    static let editDuplicateLine = CommandID("edit.duplicateLine")
    static let editMoveLineUp = CommandID("edit.moveLineUp")
    static let editMoveLineDown = CommandID("edit.moveLineDown")
    static let editJoinLines = CommandID("edit.joinLines")
    static let editTrimTrailingWhitespace = CommandID("edit.trimTrailingWhitespace")
    static let editUppercase = CommandID("edit.uppercase")
    static let editLowercase = CommandID("edit.lowercase")
    static let editSortLines = CommandID("edit.sortLines")
    static let editReverseLines = CommandID("edit.reverseLines")
    static let editIndent = CommandID("edit.indent")
    static let editOutdent = CommandID("edit.outdent")
    static let editToggleComment = CommandID("edit.toggleComment")
    static let editToggleInputMode = CommandID("edit.toggleInputMode")
    static let editMoveWordLeft = CommandID("edit.moveWordLeft")
    static let editMoveWordRight = CommandID("edit.moveWordRight")
    static let editMoveParagraphStart = CommandID("edit.moveParagraphStart")
    static let editMoveParagraphEnd = CommandID("edit.moveParagraphEnd")
    static let editDeleteWordBackward = CommandID("edit.deleteWordBackward")
    static let editDeleteWordForward = CommandID("edit.deleteWordForward")
    static let editTitlecase = CommandID("edit.titlecase")
    static let editCompleteWord = CommandID("edit.completeWord")
    static let convertHalfWidth = CommandID("convert.halfWidth")
    static let convertFullWidth = CommandID("convert.fullWidth")
    static let convertHiragana = CommandID("convert.hiragana")
    static let convertKatakana = CommandID("convert.katakana")
    static let convertTabsToSpaces = CommandID("convert.tabsToSpaces")
    static let convertSpacesToTabs = CommandID("convert.spacesToTabs")
    static let convertHalfWidthAlphanumeric = CommandID("convert.halfWidthAlphanumeric")
    static let convertFullWidthAlphanumeric = CommandID("convert.fullWidthAlphanumeric")
    static let convertHalfWidthKatakana = CommandID("convert.halfWidthKatakana")
    static let convertFullWidthKatakana = CommandID("convert.fullWidthKatakana")
    static let convertPipelineDialog = CommandID("convert.pipelineDialog")
    static let insertDateTime = CommandID("insert.dateTime")
    static let insertNewline = CommandID("insert.newline")
    static let insertTab = CommandID("insert.tab")
    static let insertPageBreak = CommandID("insert.pageBreak")
    static let insertBlankLine = CommandID("insert.blankLine")
    static let insertCurrentFileName = CommandID("insert.currentFileName")
    static let insertFileContents = CommandID("insert.fileContents")
    static let insertControlCode = CommandID("insert.controlCode")
    static let viewToggleTableMode = CommandID("view.toggleTableMode")
    static let viewToggleVerticalLayout = CommandID("view.toggleVerticalLayout")
    static let viewToggleColumnLayout = CommandID("view.toggleColumnLayout")
    static let viewToggleLineNumbers = CommandID("view.toggleLineNumbers")
    static let viewToggleHeading = CommandID("view.toggleHeading")
    static let viewToggleFunctionKeys = CommandID("view.toggleFunctionKeys")
    static let viewToggleStatusBar = CommandID("view.toggleStatusBar")
    static let viewToggleOutputPane = CommandID("view.toggleOutputPane")
    static let viewFocusOutputPane = CommandID("view.focusOutputPane")
    static let navigateMarkerRed = CommandID("navigate.markerRed")
    static let navigateMarkerYellow = CommandID("navigate.markerYellow")
    static let navigateMarkerBlue = CommandID("navigate.markerBlue")
    static let navigateNextMarker = CommandID("navigate.nextMarker")
    static let navigatePreviousMarker = CommandID("navigate.previousMarker")
    static let navigateClearMarkers = CommandID("navigate.clearMarkers")
    static let navigateHighlightList = CommandID("navigate.highlightList")
    static let viewSplitVertical = CommandID("view.splitVertical")
    static let viewSplitHorizontal = CommandID("view.splitHorizontal")
    static let viewCloseSplit = CommandID("view.closeSplit")
    static let viewToggleLinkedScrolling = CommandID("view.toggleLinkedScrolling")
    static let navigateCompareNextDocument = CommandID("navigate.compareNextDocument")
    static let navigateNextDifference = CommandID("navigate.nextDifference")
    static let navigatePreviousDifference = CommandID("navigate.previousDifference")
    static let navigateMergeDifferenceFromRight = CommandID("navigate.mergeDifferenceFromRight")
    static let navigateGenerateTags = CommandID("navigate.generateTags")
    static let navigateTagJump = CommandID("navigate.tagJump")
    static let navigateDirectTagJump = CommandID("navigate.directTagJump")
    static let navigateBackTagJump = CommandID("navigate.backTagJump")
    static let navigateToggleBookmark = CommandID("navigate.toggleBookmark")
    static let navigateNextBookmark = CommandID("navigate.nextBookmark")
    static let navigatePreviousBookmark = CommandID("navigate.previousBookmark")
    static let navigateClearBookmarks = CommandID("navigate.clearBookmarks")
    static let navigateBookmarkList = CommandID("navigate.bookmarkList")
    static let navigateToggleFold = CommandID("navigate.toggleFold")
    static let navigateCollapseAllFolds = CommandID("navigate.collapseAllFolds")
    static let navigateExpandAllFolds = CommandID("navigate.expandAllFolds")
    static let navigateBeginPartialOutline = CommandID("navigate.beginPartialOutline")
    static let navigateEndPartialOutline = CommandID("navigate.endPartialOutline")
}

/// The command definitions for MaruEdit's current static menu actions.
/// Each one is a thin wrapper around the equivalent `AppCoordinator`
/// method — the same method the menu called directly before M1-03,
/// unchanged in behavior, just invoked through the registry now.
@MainActor
enum AppCommands {
    static func registerAll(in registry: CommandRegistry) {
        registry.register(CommandDefinition(id: .appSettings, title: "Settings...") { ctx in
            ctx.coordinator.showSettings()
        })
        registry.register(CommandDefinition(id: .appMacroMenu, title: "Macro Menu") { ctx in
            ctx.coordinator.showMacroMenu()
        })
        registry.register(CommandDefinition(id: .macroStartRecording, title: "Start Recording") { $0.coordinator.startMacroRecording() })
        registry.register(CommandDefinition(id: .macroStopRecording, title: "Stop Recording") { $0.coordinator.stopMacroRecording() })
        registry.register(CommandDefinition(id: .macroPlayRecording, title: "Play Recorded Commands") { $0.coordinator.playMacroRecording() })
        registry.register(CommandDefinition(id: .macroSaveRecording, title: "Save Recording as Macro…") { $0.coordinator.saveMacroRecording() })
        registry.register(CommandDefinition(id: .appHelp, title: "MaruEdit Help") {
            $0.coordinator.showHelp()
        })
        registry.register(CommandDefinition(id: .helpMacros, title: "Macro Help") {
            $0.coordinator.showMacroHelp()
        })
        registry.register(CommandDefinition(id: .helpShortcuts, title: "Keyboard Shortcut Reference") {
            $0.coordinator.showShortcutReference()
        })
        registry.register(CommandDefinition(id: .helpCheckUpdates, title: "Check for Updates…") {
            $0.coordinator.checkForUpdates()
        })
        registry.register(CommandDefinition(id: .helpSupport, title: "Support and Report an Issue…") {
            $0.coordinator.showSupport()
        })
        registry.register(CommandDefinition(id: .helpConfigureExternal, title: "Configure External Help…") {
            $0.coordinator.showExternalHelpConfiguration()
        })
        let externalHelpIDs: [CommandID] = [
            .helpExternal1, .helpExternal2, .helpExternal3,
            .helpExternal4, .helpExternal5, .helpExternal6,
        ]
        for (slot, id) in externalHelpIDs.enumerated() {
            registry.register(CommandDefinition(
                id: id, title: "External Help \(slot + 1)",
                isEnabled: { $0.coordinator.hasExternalHelp(slot: slot) },
                execute: { $0.coordinator.openExternalHelp(slot: slot) }))
        }
        registry.register(CommandDefinition(id: .otherFileTypeProfiles, title: "File-Type Profiles…") {
            $0.coordinator.showFileTypeProfiles()
        })
        registry.register(CommandDefinition(id: .otherKeyAssignments, title: "Key Assignments…") {
            $0.coordinator.showKeyAssignments()
        })
        registry.register(CommandDefinition(id: .otherCommandList, title: "Command List…") {
            $0.coordinator.showMenuCustomization()
        })
        registry.register(CommandDefinition(id: .otherClearFindHistory, title: "Clear Find History") { $0.coordinator.clearHistory(.find) })
        registry.register(CommandDefinition(id: .otherClearReplaceHistory, title: "Clear Replace History") { $0.coordinator.clearHistory(.replace) })
        registry.register(CommandDefinition(id: .otherClearGrepHistory, title: "Clear Grep History") { $0.coordinator.clearHistory(.grep) })
        registry.register(CommandDefinition(id: .otherClearClipboardHistory, title: "Clear Clipboard History") { $0.coordinator.clearClipboardHistory() })
        registry.register(CommandDefinition(id: .otherClearRecentFiles, title: "Clear Recent Files") { $0.coordinator.clearRecentFiles() })
        registry.register(CommandDefinition(id: .otherClearRecentFolders, title: "Clear Recent Project Folders") { $0.coordinator.clearRecentFolders() })
        registry.register(CommandDefinition(id: .otherClearRecentWorkspaces, title: "Clear Recent Workspaces") { $0.coordinator.clearRecentWorkspaces() })
        registry.register(CommandDefinition(id: .otherClearRecentEncodings, title: "Clear Recent Encodings") { $0.coordinator.clearRecentEncodings() })
        registry.register(CommandDefinition(id: .otherClearAllHistories, title: "Clear All Histories") { $0.coordinator.clearAllHistories() })
        registry.register(CommandDefinition(id: .otherToggleFreeCursor, title: "Free Cursor") { $0.coordinator.toggleFreeCursor() })
        registry.register(CommandDefinition(id: .otherExportSettings, title: "Export Settings…") { $0.coordinator.showSettingsExportPanel() })
        registry.register(CommandDefinition(id: .otherImportSettings, title: "Import Settings…") { $0.coordinator.showSettingsImportPanel() })
        registry.register(CommandDefinition(id: .otherRestoreSettings, title: "Restore Default Settings…") { $0.coordinator.confirmRestoreDefaultSettings() })
        registry.register(CommandDefinition(id: .otherJapaneseUserDictionary, title: "Japanese User Dictionary…") { $0.coordinator.showJapaneseUserDictionaryHelp() })
        registry.register(CommandDefinition(id: .fileNew, title: "New File") { ctx in
            ctx.coordinator.newDocument()
        })
        registry.register(CommandDefinition(id: .fileNewFromTemplate, title: "New from Template…") { $0.coordinator.newDocumentFromTemplate() })
        registry.register(CommandDefinition(id: .fileOpen, title: "Open...") { ctx in
            ctx.coordinator.openDocument()
        })
        registry.register(CommandDefinition(id: .fileOpenFolder, title: "Open Folder...") { ctx in
            ctx.coordinator.openFolderPanel()
        })
        registry.register(CommandDefinition(id: .fileSave, title: "Save") { ctx in
            ctx.coordinator.saveDocument()
        })
        registry.register(CommandDefinition(id: .fileSaveAs, title: "Save As...") { ctx in
            ctx.coordinator.saveDocumentAs()
        })
        registry.register(CommandDefinition(id: .fileSaveAll, title: "Save All") { $0.coordinator.saveAllDocuments() })
        registry.register(CommandDefinition(id: .fileSaveAllModified, title: "Save All Modified Files") { $0.coordinator.saveAllModifiedDocuments() })
        registry.register(CommandDefinition(id: .fileSaveLF, title: "Save with LF Line Endings") { $0.coordinator.saveDocumentWithLFLineEndings() })
        registry.register(CommandDefinition(id: .fileSaveAndClose, title: "Save and Close") { $0.coordinator.saveAndCloseCurrentTab() })
        registry.register(CommandDefinition(id: .fileSaveAllAndClose, title: "Save All and Close") { $0.coordinator.saveAllAndClose() })
        registry.register(CommandDefinition(id: .fileDiscardAndClose, title: "Discard and Close") { $0.coordinator.discardAndCloseCurrentTab() })
        registry.register(CommandDefinition(id: .fileDiscardAllAndClose, title: "Discard All and Close") { $0.coordinator.discardAllAndClose() })
        registry.register(CommandDefinition(id: .fileOpenCursorTargetAssociated, title: "Open Target with Associated Application") { $0.coordinator.openCursorTargetWithAssociatedApplication() })
        registry.register(CommandDefinition(id: .fileOpenCursorTargetInEditor, title: "Open Target in MaruEdit") { $0.coordinator.openCursorTargetInMaruEdit() })
        registry.register(CommandDefinition(id: .fileCloseTab, title: "Close Tab") { ctx in
            ctx.coordinator.closeCurrentTab()
        })
        registry.register(CommandDefinition(id: .windowNextTab, title: "Next Tab") {
            $0.coordinator.selectNextTab()
        })
        registry.register(CommandDefinition(id: .windowPreviousTab, title: "Previous Tab") {
            $0.coordinator.selectPreviousTab()
        })
        registry.register(CommandDefinition(id: .windowTabList, title: "Tab List…") { $0.coordinator.showTabList() })
        registry.register(CommandDefinition(id: .windowCloseOtherTabs, title: "Close Other Tabs") { $0.coordinator.closeOtherTabs() })
        registry.register(CommandDefinition(id: .windowCloseTabsLeft, title: "Close Tabs to the Left") { $0.coordinator.closeTabsLeft() })
        registry.register(CommandDefinition(id: .windowCloseTabsRight, title: "Close Tabs to the Right") { $0.coordinator.closeTabsRight() })
        registry.register(CommandDefinition(id: .windowFocusEditor, title: "Focus Editor") { $0.coordinator.focusEditor() })
        registry.register(CommandDefinition(id: .windowFocusUtilityPane, title: "Focus Utility Pane") { $0.coordinator.focusUtilityPane() })
        registry.register(CommandDefinition(id: .fileClearRecoveryData, title: "Clear Recovery Data...") { ctx in
            ctx.coordinator.clearRecoveryData()
        })
        registry.register(CommandDefinition(id: .filePageSetup, title: "Page Setup…") { $0.coordinator.showPageSetup() })
        registry.register(CommandDefinition(id: .filePrint, title: "Print…") { $0.coordinator.printDocument() })
        registry.register(CommandDefinition(id: .fileReload, title: "Reload from Disk") { $0.coordinator.reloadDocument() })
        registry.register(CommandDefinition(id: .fileToggleViewMode, title: "View Mode") { $0.coordinator.toggleViewMode() })
        registry.register(CommandDefinition(id: .fileProperties, title: "File Properties…") { $0.coordinator.showFileProperties() })
        registry.register(CommandDefinition(id: .fileAppendRead, title: "Append Read…") { $0.coordinator.appendRead() })
        registry.register(CommandDefinition(id: .fileAppendSave, title: "Append Save…") { $0.coordinator.appendSave() })
        registry.register(CommandDefinition(id: .fileRename, title: "Rename File…") { $0.coordinator.renameFile() })
        registry.register(CommandDefinition(id: .fileOpenPartial, title: "Open Partial File…") { $0.coordinator.openPartialFile() })
        registry.register(CommandDefinition(id: .fileOpenBinary, title: "Open in Binary Mode…") { $0.coordinator.openBinaryFile() })
        registry.register(CommandDefinition(id: .fileProjectHistory, title: "Project History…") { $0.coordinator.showProjectHistory() })
        registry.register(CommandDefinition(id: .fileSaveWorkspace, title: "Save Workspace As…") { $0.coordinator.saveWorkspaceAs() })
        registry.register(CommandDefinition(id: .fileOpenWorkspace, title: "Open Workspace…") { $0.coordinator.openWorkspace() })
        registry.register(CommandDefinition(id: .fileWorkspaceHistory, title: "Workspace History…") { $0.coordinator.showWorkspaceHistory() })
        registry.register(CommandDefinition(id: .fileCloseAndOpen, title: "Close and Open…") { $0.coordinator.closeAndOpen() })
        registry.register(CommandDefinition(id: .searchFind, title: "Find...") { ctx in
            ctx.coordinator.showFind()
        })
        registry.register(CommandDefinition(id: .searchReplace, title: "Find and Replace...") { ctx in
            ctx.coordinator.showReplace()
        })
        registry.register(CommandDefinition(id: .searchReplaceAll, title: "Replace All") { ctx in
            ctx.coordinator.replaceAll()
        })
        registry.register(CommandDefinition(id: .searchFindNext, title: "Find Next") { ctx in
            ctx.coordinator.findNext()
        })
        registry.register(CommandDefinition(id: .searchFindPrevious, title: "Find Previous") { ctx in
            ctx.coordinator.findPrevious()
        })
        registry.register(CommandDefinition(id: .searchGoToLine, title: "Go to Line...") { ctx in
            ctx.coordinator.showGoToLine()
        })
        registry.register(CommandDefinition(id: .searchQuickOpen, title: "Quick Open...") { ctx in
            ctx.coordinator.showQuickOpen()
        })
        registry.register(CommandDefinition(id: .searchGrep, title: "Find in Folder...") { ctx in
            ctx.coordinator.showGrep()
        })
        registry.register(CommandDefinition(id: .searchGrepCurrentDocument, title: "Grep Current Document") { $0.coordinator.grepCurrentDocument() })
        registry.register(CommandDefinition(id: .searchGrepOpenDocuments, title: "Grep All Open Documents") { $0.coordinator.grepOpenDocuments() })
        registry.register(CommandDefinition(id: .searchRefineGrepResults, title: "Refine Grep Results") { $0.coordinator.refineGrepResults() })
        registry.register(CommandDefinition(id: .searchOutputGrepDocument, title: "Output Grep Results as Document") { $0.coordinator.outputGrepResultsAsDocument() })
        registry.register(CommandDefinition(id: .searchClearHistory, title: "Clear Search History") { ctx in
            ctx.coordinator.clearSearchHistory()
        })
        registry.register(CommandDefinition(id: .searchToggleCaseSensitive, title: "Case Sensitive") { $0.coordinator.toggleFindOption(.caseSensitive) })
        registry.register(CommandDefinition(id: .searchToggleWholeWord, title: "Whole Word") { $0.coordinator.toggleFindOption(.wholeWord) })
        registry.register(CommandDefinition(id: .searchToggleRegex, title: "Regular Expression") { $0.coordinator.toggleFindOption(.regularExpression) })
        registry.register(CommandDefinition(id: .searchToggleFuzzy, title: "Fuzzy Width Search") { $0.coordinator.toggleFindOption(.fuzzy) })
        registry.register(CommandDefinition(id: .searchNextEditMark, title: "Next Edit Mark") { $0.coordinator.nextEditMark() })
        registry.register(CommandDefinition(id: .searchPreviousEditMark, title: "Previous Edit Mark") { $0.coordinator.previousEditMark() })
        registry.register(CommandDefinition(id: .searchClearEditMarks, title: "Clear Edit Marks") { $0.coordinator.clearEditMarks() })
        registry.register(CommandDefinition(id: .searchToggleHighlight, title: "Highlight Search String") { $0.coordinator.toggleSearchHighlight() })
        registry.register(CommandDefinition(id: .searchSelectAllMatches, title: "Select All Matches") { $0.coordinator.selectAllSearchMatches() })
        registry.register(CommandDefinition(id: .searchColorAllMatches, title: "Color All Matches") { $0.coordinator.colorAllSearchMatches() })
        registry.register(CommandDefinition(id: .searchClearMatchColors, title: "Clear Match Colors") { $0.coordinator.clearSearchColors() })
        registry.register(CommandDefinition(id: .searchListAllMatches, title: "List All Matches") { $0.coordinator.listAllSearchMatches() })
        registry.register(CommandDefinition(id: .searchReturnToStart, title: "Return to Search Start") { $0.coordinator.returnToSearchStart() })
        registry.register(CommandDefinition(id: .searchSetRange, title: "Set Selection as Search Range") { $0.coordinator.setSearchRangeFromSelection() })
        registry.register(CommandDefinition(id: .searchSelectRange, title: "Select Search Range") { $0.coordinator.selectSearchRange() })
        registry.register(CommandDefinition(id: .searchClearRange, title: "Clear Search Range") { $0.coordinator.clearSearchRange() })
        registry.register(CommandDefinition(id: .viewToggleSidebar, title: "Toggle Sidebar") { ctx in
            ctx.coordinator.toggleSidebar()
        })
        registry.register(CommandDefinition(id: .viewToggleWrap, title: "Wrap Lines") {
            $0.coordinator.toggleWrapLines()
        })
        registry.register(CommandDefinition(id: .viewToggleSpaces, title: "Show Spaces") {
            $0.coordinator.toggleInvisible(\.spaces)
        })
        registry.register(CommandDefinition(id: .viewToggleTabs, title: "Show Tabs") {
            $0.coordinator.toggleInvisible(\.tabs)
        })
        registry.register(CommandDefinition(id: .viewToggleLineEndings, title: "Show Line Endings") {
            $0.coordinator.toggleInvisible(\.lineEndings)
        })
        registry.register(CommandDefinition(
            id: .viewToggleFullWidthSpaces, title: "Show Full-Width Spaces") {
                $0.coordinator.toggleInvisible(\.fullWidthSpaces)
            })
        registry.register(CommandDefinition(id: .viewTabWidth2, title: "2 Spaces") {
            $0.coordinator.setTabWidth(2)
        })
        registry.register(CommandDefinition(id: .viewTabWidth4, title: "4 Spaces") {
            $0.coordinator.setTabWidth(4)
        })
        registry.register(CommandDefinition(id: .viewTabWidth8, title: "8 Spaces") {
            $0.coordinator.setTabWidth(8)
        })
        registry.register(CommandDefinition(id: .viewShowFonts, title: "Show Fonts") {
            $0.coordinator.showFontPanel()
        })
        registry.register(CommandDefinition(id: .viewCustomizeMenus, title: "Customize Menus...") {
            $0.coordinator.showMenuCustomization()
        })
        registry.register(CommandDefinition(id: .viewToggleRuler, title: "Show Character Ruler") { $0.coordinator.toggleRuler() })
        registry.register(CommandDefinition(id: .viewRulerInterval8, title: "Ruler: 8-Column Units") { $0.coordinator.setRulerInterval(8) })
        registry.register(CommandDefinition(id: .viewRulerInterval10, title: "Ruler: 10-Column Units") { $0.coordinator.setRulerInterval(10) })
        registry.register(CommandDefinition(id: .viewToggleTabStops, title: "Show Tab Stops on Ruler") { $0.coordinator.toggleRulerTabStops() })
        registry.register(CommandDefinition(id: .editAddCursorAbove, title: "Add Cursor Above") { $0.coordinator.addCursorAbove() })
        registry.register(CommandDefinition(id: .editAddCursorBelow, title: "Add Cursor Below") { $0.coordinator.addCursorBelow() })
        registry.register(CommandDefinition(id: .editSelectNextOccurrence, title: "Select Next Occurrence") { $0.coordinator.selectNextOccurrence() })
        registry.register(CommandDefinition(id: .editSelectAllOccurrences, title: "Select All Occurrences") { $0.coordinator.selectAllOccurrences() })
        registry.register(CommandDefinition(id: .editUndoLastAddedCursor, title: "Undo Last Added Cursor") { $0.coordinator.undoLastAddedCursor() })
        registry.register(CommandDefinition(id: .editBeginColumnSelection, title: "Begin Column Selection") { $0.coordinator.beginColumnSelection() })
        registry.register(CommandDefinition(id: .editSelectWord, title: "Select Word") { $0.coordinator.selectCurrentWord() })
        registry.register(CommandDefinition(id: .editSelectLine, title: "Select Line") { $0.coordinator.selectCurrentLine() })
        registry.register(CommandDefinition(id: .editSelectParagraph, title: "Select Paragraph") { $0.coordinator.selectCurrentParagraph() })
        registry.register(CommandDefinition(id: .editCopyQuoted, title: "Copy with Quote Prefix") { $0.coordinator.copyWithQuotePrefix() })
        registry.register(CommandDefinition(id: .editPasteQuoted, title: "Paste Removing Quote Prefix") { $0.coordinator.pasteRemovingQuotePrefix() })
        registry.register(CommandDefinition(id: .editClipboardHistory, title: "Clipboard History…") { $0.coordinator.showClipboardHistory() })
        registry.register(CommandDefinition(id: .editRestoreDeletion, title: "Restore Last Deleted Text") { $0.coordinator.restoreLastDeletedText() })
        registry.register(CommandDefinition(id: .editCorrectCapsLock, title: "Correct Caps Lock Mistake") { $0.coordinator.correctCapsLockMistake() })
        registry.register(CommandDefinition(id: .editReconvert, title: "Reconvert with Input Method") { $0.coordinator.reconvertWithInputMethod() })
        registry.register(CommandDefinition(id: .editAppendCopy, title: "Append Copy") { $0.coordinator.appendCopy() })
        registry.register(CommandDefinition(id: .editAppendCut, title: "Append Cut") { $0.coordinator.appendCut() })
        registry.register(CommandDefinition(id: .editDeleteToLineStart, title: "Delete to Start of Line") { $0.coordinator.deleteToLineStart() })
        registry.register(CommandDefinition(id: .editDeleteToLineEnd, title: "Delete to End of Line") { $0.coordinator.deleteToLineEnd() })
        registry.register(CommandDefinition(id: .editInvertSelections, title: "Invert Selections") { $0.coordinator.invertSelections() })
        registry.register(CommandDefinition(id: .editReserveSelections, title: "Reserve Selections") { $0.coordinator.reserveSelections() })
        registry.register(CommandDefinition(id: .editRestoreReservedSelections, title: "Restore Reserved Selections") { $0.coordinator.restoreReservedSelections() })
        registry.register(CommandDefinition(id: .editBoxPaste, title: "BOX Paste") { $0.coordinator.boxPaste() })
        registry.register(CommandDefinition(id: .editPastePreviousClipboard, title: "Paste Previous Clipboard") { $0.coordinator.pastePreviousClipboard() })
        registry.register(CommandDefinition(
            id: .editRepeatLastOperation, title: "Repeat Last Edit",
            isEnabled: { $0.coordinator.canRepeatLastEdit },
            execute: { $0.coordinator.repeatLastEdit() }))
        registerLineCommands(in: registry)
        registry.register(CommandDefinition(id: .editToggleInputMode, title: "Toggle Insert/Overwrite Mode") { $0.coordinator.toggleInputMode() })
        registry.register(CommandDefinition(id: .editMoveWordLeft, title: "Move Word Left") { $0.coordinator.moveWordLeft() })
        registry.register(CommandDefinition(id: .editMoveWordRight, title: "Move Word Right") { $0.coordinator.moveWordRight() })
        registry.register(CommandDefinition(id: .editMoveParagraphStart, title: "Move to Paragraph Start") { $0.coordinator.moveToParagraphStart() })
        registry.register(CommandDefinition(id: .editMoveParagraphEnd, title: "Move to Paragraph End") { $0.coordinator.moveToParagraphEnd() })
        registry.register(CommandDefinition(id: .editDeleteWordBackward, title: "Delete Word Backward") { $0.coordinator.deleteWordBackward() })
        registry.register(CommandDefinition(id: .editDeleteWordForward, title: "Delete Word Forward") { $0.coordinator.deleteWordForward() })
        registry.register(CommandDefinition(id: .editTitlecase, title: "Convert to Title Case") { $0.coordinator.performLineCommand(.titlecase) })
        registry.register(CommandDefinition(id: .editCompleteWord, title: "Complete Word") { $0.coordinator.showCompletions() })
        let conversions: [(CommandID, String, LineEditCommand)] = [
            (.convertHalfWidth, "Convert to Half-Width", .halfWidth),
            (.convertFullWidth, "Convert to Full-Width", .fullWidth),
            (.convertHiragana, "Convert to Hiragana", .hiragana),
            (.convertKatakana, "Convert to Katakana", .katakana),
            (.convertTabsToSpaces, "Convert Tabs to Spaces", .tabsToSpaces),
            (.convertSpacesToTabs, "Convert Leading Spaces to Tabs", .spacesToTabs),
            (.convertHalfWidthAlphanumeric, "Alphanumerics/Symbols/Spaces to Half-Width", .halfWidthAlphanumeric),
            (.convertFullWidthAlphanumeric, "Alphanumerics/Symbols/Spaces to Full-Width", .fullWidthAlphanumeric),
            (.convertHalfWidthKatakana, "Katakana Only to Half-Width", .halfWidthKatakana),
            (.convertFullWidthKatakana, "Katakana Only to Full-Width", .fullWidthKatakana),
        ]
        for (id, title, command) in conversions {
            registry.register(CommandDefinition(id: id, title: title) {
                $0.coordinator.performLineCommand(command)
            })
        }
        registry.register(CommandDefinition(id: .convertPipelineDialog, title: "Conversion Pipeline…") {
            $0.coordinator.showConversionPipeline()
        })
        registry.register(CommandDefinition(id: .insertDateTime, title: "Date and Time") {
            $0.coordinator.insertDateTime()
        })
        registry.register(CommandDefinition(id: .insertNewline, title: "Newline") { $0.coordinator.insertNewline() })
        registry.register(CommandDefinition(id: .insertTab, title: "Tab") { $0.coordinator.insertTab() })
        registry.register(CommandDefinition(id: .insertPageBreak, title: "Page Break") {
            $0.coordinator.insertPageBreak()
        })
        registry.register(CommandDefinition(id: .insertBlankLine, title: "Insert Blank Line Above") { $0.coordinator.insertBlankLine() })
        registry.register(CommandDefinition(id: .insertCurrentFileName, title: "Current File Name") { $0.coordinator.insertCurrentFileName() })
        registry.register(CommandDefinition(id: .insertFileContents, title: "File Contents…") {
            $0.coordinator.insertFileContents()
        })
        registry.register(CommandDefinition(id: .insertControlCode, title: "Control Code…") {
            $0.coordinator.insertControlCode()
        })
        registry.register(CommandDefinition(id: .viewToggleTableMode, title: "CSV/TSV Table Mode") { $0.coordinator.toggleTableMode() })
        registry.register(CommandDefinition(id: .viewToggleVerticalLayout, title: "Vertical Writing Mode") { $0.coordinator.toggleVerticalLayout() })
        registry.register(CommandDefinition(id: .viewToggleColumnLayout, title: "Column Layout Mode") { $0.coordinator.toggleColumnLayout() })
        registry.register(CommandDefinition(id: .viewToggleLineNumbers, title: "Show Line Numbers") { $0.coordinator.toggleLineNumbers() })
        registry.register(CommandDefinition(id: .viewToggleHeading, title: "Show Heading Bar") { $0.coordinator.toggleClassicHeading() })
        registry.register(CommandDefinition(id: .viewToggleFunctionKeys, title: "Show Function-Key Bar") { $0.coordinator.toggleFunctionKeyStrip() })
        registry.register(CommandDefinition(id: .viewToggleStatusBar, title: "Show Status Bar") { $0.coordinator.toggleStatusBar() })
        registry.register(CommandDefinition(id: .viewToggleOutputPane, title: "Show Output Pane") { $0.coordinator.toggleOutputPane() })
        registry.register(CommandDefinition(id: .viewFocusOutputPane, title: "Focus Output Pane") { $0.coordinator.focusOutputPane() })
        registry.register(CommandDefinition(id: .navigateMarkerRed, title: "Toggle Red Marker") { $0.coordinator.toggleMarker(.red) })
        registry.register(CommandDefinition(id: .navigateMarkerYellow, title: "Toggle Yellow Marker") { $0.coordinator.toggleMarker(.yellow) })
        registry.register(CommandDefinition(id: .navigateMarkerBlue, title: "Toggle Blue Marker") { $0.coordinator.toggleMarker(.blue) })
        registry.register(CommandDefinition(id: .navigateNextMarker, title: "Next Marker") { $0.coordinator.nextMarker() })
        registry.register(CommandDefinition(id: .navigatePreviousMarker, title: "Previous Marker") { $0.coordinator.previousMarker() })
        registry.register(CommandDefinition(id: .navigateClearMarkers, title: "Clear Markers") { $0.coordinator.clearMarkers() })
        registry.register(CommandDefinition(id: .navigateHighlightList, title: "Highlight List…") { $0.coordinator.showHighlightList() })
        registry.register(CommandDefinition(id: .viewSplitVertical, title: "Split Editor Vertically") { $0.coordinator.splitEditorVertical() })
        registry.register(CommandDefinition(id: .viewSplitHorizontal, title: "Split Editor Horizontally") { $0.coordinator.splitEditorHorizontal() })
        registry.register(CommandDefinition(id: .viewCloseSplit, title: "Close Editor Split") { $0.coordinator.closeEditorSplit() })
        registry.register(CommandDefinition(id: .viewToggleLinkedScrolling, title: "Linked Editor Scrolling") { $0.coordinator.toggleLinkedEditorScrolling() })
        registry.register(CommandDefinition(id: .navigateCompareNextDocument, title: "Compare with Next Document") { $0.coordinator.compareWithNextDocument() })
        registry.register(CommandDefinition(id: .navigateNextDifference, title: "Next Difference") { $0.coordinator.nextDifference() })
        registry.register(CommandDefinition(id: .navigatePreviousDifference, title: "Previous Difference") { $0.coordinator.previousDifference() })
        registry.register(CommandDefinition(id: .navigateMergeDifferenceFromRight, title: "Accept Difference from Right") { $0.coordinator.mergeCurrentDifferenceFromRight() })
        registry.register(CommandDefinition(id: .navigateGenerateTags, title: "Generate Tags File…") { $0.coordinator.generateTagsFile() })
        registry.register(CommandDefinition(id: .navigateTagJump, title: "Jump to Tag…") { $0.coordinator.showTagJump() })
        registry.register(CommandDefinition(id: .navigateDirectTagJump, title: "Direct Tag Jump") { $0.coordinator.directTagJump() })
        registry.register(CommandDefinition(id: .navigateBackTagJump, title: "Back from Tag") { $0.coordinator.backTagJump() })
        registry.register(CommandDefinition(id: .navigateToggleBookmark, title: "Toggle Bookmark") { $0.coordinator.toggleBookmark() })
        registry.register(CommandDefinition(id: .navigateNextBookmark, title: "Next Bookmark") { $0.coordinator.nextBookmark() })
        registry.register(CommandDefinition(id: .navigatePreviousBookmark, title: "Previous Bookmark") { $0.coordinator.previousBookmark() })
        registry.register(CommandDefinition(id: .navigateClearBookmarks, title: "Clear Bookmarks") { $0.coordinator.clearBookmarks() })
        registry.register(CommandDefinition(id: .navigateBookmarkList, title: "Bookmark List…") { $0.coordinator.showBookmarkList() })
        registry.register(CommandDefinition(id: .navigateToggleFold, title: "Toggle Fold") { $0.coordinator.toggleFold() })
        registry.register(CommandDefinition(id: .navigateBeginPartialOutline, title: "Edit Current Outline Region") { $0.coordinator.beginPartialOutlineEditing() })
        registry.register(CommandDefinition(id: .navigateEndPartialOutline, title: "Show Full Document") { $0.coordinator.endPartialOutlineEditing() })
        registry.register(CommandDefinition(id: .navigateCollapseAllFolds, title: "Collapse All Folds") { $0.coordinator.collapseAllFolds() })
        registry.register(CommandDefinition(id: .navigateExpandAllFolds, title: "Expand All Folds") { $0.coordinator.expandAllFolds() })
    }

    private static func registerLineCommands(in registry: CommandRegistry) {
        let commands: [(CommandID, String, LineEditCommand)] = [
            (.editDeleteLine, "Delete Line", .delete),
            (.editDuplicateLine, "Duplicate Line/Selection", .duplicate),
            (.editMoveLineUp, "Move Line Up", .moveUp),
            (.editMoveLineDown, "Move Line Down", .moveDown),
            (.editJoinLines, "Join Lines", .join),
            (.editTrimTrailingWhitespace, "Trim Trailing Whitespace", .trimTrailingWhitespace),
            (.editUppercase, "Convert to Uppercase", .uppercase),
            (.editLowercase, "Convert to Lowercase", .lowercase),
            (.editSortLines, "Sort Lines", .sort),
            (.editReverseLines, "Reverse Lines", .reverse),
            (.editIndent, "Indent", .indent),
            (.editOutdent, "Outdent", .outdent),
            (.editToggleComment, "Toggle Comment", .toggleComment),
        ]
        for (id, title, command) in commands {
            registry.register(CommandDefinition(id: id, title: title) {
                $0.coordinator.performLineCommand(command)
            })
        }
    }
}
